### PR TITLE
Make the question index a part of the state

### PR DESCRIPTION
**Pull request by jdalegonzalez**
This is a proposed fix for issue #121.

I didn't try fixing the button title issue, I only fixed the question numbers issue.  I also only made the number piece a part of state.  Based on the way the knockout code looks, perhaps the right fix is to make the entire title a part of the state.

### CODE REVIEW

**Comment by andrewtelnov** [comment]
@jdalegonzalez Thank you!

**Comment by jdalegonzalez** [comment]
You bet.   Thanks for merging.  How frequently do you update the npm repo?

**Comment by andrewtelnov** [comment]
Commonly one time per a week.
I think, it will be changed. We will start to push the project in the next year. We will go to semantic versions and all paths will be on npm.
The first step is to integrate our functional tests with Travis.

**Comment by andrewtelnov** [comment]
Sorry - one time in two weeks :)

**Comment by jdalegonzalez** [comment]
Thanks Andrew.  I appreciate it.



On November 25, 2016 at 9:41:14 AM, Andrew (notifications@github.com) wrote:

Sorry - one time in two weeks :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/andrewtelnov/surveyjs/pull/122#issuecomment-262969572>,
or mute the thread

**Pull request merged**
